### ISSUE TITLE
Is it OK to this list on CKAN?

### ISSUE THREAD

**Issue by HebaruSan** [Sigma88/Sigma-LoadingScreens#12]
May we please list this on CKAN? We have a request to install it from the copy bundled in Gameslinx's Planet Overhaul, but we prefer to track each mod's individual downloads and set up proper dependencies instead, and Sigma-LoadingScreens isn't yet in the index.

**Comment by Galileo88** [comment]
Sigma Loading Screens was developed as a tool for modders, not an end user mod. It is meant to be bundled, not downloaded separately. Having it listed in CKAN will only create more issues for Sigma as many users will not know how to use it properly and will inundate him with bug reports.

**Comment by HebaruSan** [comment]
Yes, that's clear, but if a user wants to install multiple different mods that each bundle SLS, that conflict has to handled somehow. If we list it independently, then they can each depend on it and everything should work as intended. Whereas if we have to install each mod's bundled copies, then all mods that use SLS have to conflict with one another.

**Comment by Galileo88** [comment]
SLS is not intended to be located directly in the GameData folder. It's location is up to the developer of the mod. Currently, there are roughly 3 mods that use SLS and all are located inside their respective mod folders, or they should be. There is no way they will conflict.

**Comment by HebaruSan** [comment]
@Galileo88, the GPO download has it directly in GameData/LoadingScreens:

- https://spacedock.info/mod/1247

![image](https://user-images.githubusercontent.com/1559108/36625080-2aff6738-18de-11e8-902d-fc8ff1c4178b.png)

That's what I mean by causing conflicts.

**Comment by Galileo88** [comment]
Well, than that's something he will have to change then. He was told not to do that.

I do not see a benefit to having it on CKAN if its only for this one mod. That's not fair to Sigma to have to deal with the that will inevitably pop up because users of CKAN don't know any better.

Besides, GPP and GPO are not compatible anyway, and that is made very clear on the forum threads, so there is still no way these can conflict. 

and regardless, even with GPO bundling LoadingScreens incorrectly, it wouldn't conflict with the other mods currently using it.

**Comment by HebaruSan** [comment]
> He was told not to do that.

Was he, though? I just checked the forum thread and the readme, and I don't see any such instructions. Not trying to be contrarian, but I'd like to report the problem, and an authoritative reference helps a lot for that.

If modders would bundle this mod as you say they're supposed to, I agree that would eliminate the need to index it independently...

**Comment by Galileo88** [comment]
Myself, Sigma and Gameslinx talk extensively on a private discord. We hardly converse on the forums. 
Perhaps Sigma should make it more clear on his forum thread.

**Comment by HebaruSan** [comment]
I'd think the README.md would specify such things, since the forum thread is closed.
Any random modder wishing to use this mod has permission, so participation in a private Discord server probably shouldn't be a prerequisite for learning to package it.

**Comment by Galileo88** [comment]
OK then perhaps he should update the README. I'm sure it was an oversight not to include that information. Sigma's Discord link is in the forum OP for anyone that's interested. For any other questions he requires that users use GitHub, hence the closed threads. He is not unreachable, if that's what you are getting at. My particular discord where the conversation was had with Gameslinx, was private.

**Comment by Galileo88** [comment]
Ultimately this decision is up to Sigma, so I suppose you can wait on him to pop up in a few hours

**Comment by HebaruSan** [comment]
No, that's fine, I realize it's tricky to dot all the i's when releasing something publicly.

The original question seems to be answered now: No, this shouldn't be indexed independently on CKAN, but mods using it should bundle it in their own folders so it doesn't conflict. Thanks for taking the time to explain this to me!

@Sigma88, your input is welcome as well if you care to chime in, but for now I'll plan to leave things more or less as they are, and try to get GPO's packaging fixed.

**Comment by Sigma88** [comment]
I didn't read the whole bible you wrote up there because I can't be bothered.

I can answer the two questions I managed to read:

1- there is no point in adding this to ckan since the only reason to install it is if another mod bundles it, and in that case that mod netkan will include the install instructions. I'm not forbidding you to adding it to ckan, but I will complain if the netkan will cause me troules

2- gameslinx is free to put the folder wherever he wants, if that's an issue for ckan it should be solved between ckan and gameslinx

**Comment by HebaruSan** [comment]
Thanks Sigma, I think we have the GPO situation sorted out. Sorry for bothering you!
