### ISSUE TITLE
file types, path names info needed

### ISSUE THREAD

**Issue by linuxgurugamer** [Sigma88/Sigma-LoadingScreens#9]
Does this support more than dds files?

When specifying a folder path, can it accept  Windows path names like:  C:\Users\jbb\Dropbox\ScreenBackgrounds

**Comment by Sigma88** [comment]
I wrote this to support dds only by design because other types of file have much longer loading time and I didn't want to bother having to deal with loading time issues.

and the folder path must use "KSP/Unity" syntax

(I don't know if your example is from a real need, but I think it's worth noting that it is against ksp forum rules to share mods that can read/write outside of the ksp install folder)

**Comment by Sigma88** [comment]
To expand on the dds thing

I initially wrote this loader for my mods only because I needed one that was tailored around my needs.

Mostly it needed to be able to load dds files, to accept multiple cfgs, and to be bundled inside other mods (making sure that multiple copies didn't affect the plugin itself)

This is why I never bothered adding more functionality.

If you want to incorporate some bits into LSM just let me know so I can give you the permissions you need

**Comment by linuxgurugamer** [comment]
Regarding reading/writing outside the directory:

Reading is allowed and ok, writing is the problem.  And even that can be handled by being extremely specific as to what is going on, I've asked and gotten permission to publish at least two different mods which have the ability to write outside the directory.  They both default to the game directory, but can be changed.  

The example I gave was directly from another install I have using LSM, obviously on a Windows machine.  I have a common folder I use to store images I like to see on loading, obviously, since it is used by multiple installs, it has to be outside one or more game folders.  But LSM doesn't write anything except it's local config.

**Comment by linuxgurugamer** [comment]
Regarding sharing code, I'd like to incorporate a few lines of your code which prevents multiple copies of the same DLL from being loaded

**Comment by Sigma88** [comment]
[this](https://github.com/Sigma88/Sigma-LoadingScreens/blob/07e22798cad8141f435504ee67b53d9f09d8108d/%5BSource%5D/SigmaLoadingScreens/LoadingScreenSettings.cs#L38-L52) is what I use to do that

it's pretty simple so you can take that without worrying about licenses.

at most, if you want you can add a thank you note with my name for showing you my solution.


of course, make sure you replace `"Sigma88LoadingScreens"` with the name of your assembly

**Comment by Sigma88** [comment]
also, you might consider avoiding shitting on my mods in the future if you plan to ask me permission of using code from those same mods.

It will definitely help with your chances of getting what you want

**Comment by linuxgurugamer** [comment]
I'm sorry about that.  It was an unexpected find, I wasn't even aware that LSM had been replaced, and then with the issues, and after 6 hours of streaming, I was feeling pretty upset.  
Not your fault, and I'm going to post an apology in the forums.

I'll definitely include the thank you note.

**Comment by Sigma88** [comment]
no need for an apology on the forums, just come to me first if you have issues, I never say no to fixing my mods If I can 👍

**Comment by linuxgurugamer** [comment]
Thank  you, but I had to do it.  I was wrong, and I had to make it right.

Anyway, I hope we are past that, and I'll be looking into the issues this evening, hope to get you some more info tomorrow.

**Comment by Sigma88** [comment]
> Anyway, I hope we are past that

sure, no worries

>I'll be looking into the issues this evening

great 👍

**Comment by linuxgurugamer** [comment]
I'm closing this since it's not an issue, and I found the problem was actually in my install.
